# Generated by Django 4.2 on 2025-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_sharedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
