# Generated by Django 4.2 on 2025-01-14 13:45

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_videopost_video_url_videopost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[posts.validators.validate_youtube_url]),
        ),
    ]
