# Generated by Django 4.2 on 2025-01-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_videopost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_mgvuq6', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
