# Generated by Django 4.2 on 2025-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_sharedpost_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
