# Generated by Django 4.2 on 2025-01-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_videopost_name_alter_videopost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='video',
        ),
    ]
