# Generated by Django 4.2 on 2025-01-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_sharedvideopost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_alter_like_unique_together_like_video_post_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.sharedpost'),
        ),
        migrations.AddField(
            model_name='like',
            name='shared_video_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.sharedvideopost'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'post', 'video_post', 'shared_post', 'shared_video_post')},
        ),
    ]
